Home Screen Content
GDGEventsApp/GDGEventsApp pull request #18
Opened 2024-12-25 18:37 UTC by MohammadAshrf

# Pull Request Template

## Description
Provide a clear and concise description of what this pull request does. Include the purpose and context for the changes.

This pull request implements the FeaturedEventsSection, EventListSection, and TopBar with Material3 theme integration. The updates ensure consistency with the app's design, theme-based colors, typography, and shapes.
---

## Changes Made
List the changes introduced in this pull request:
- Added FeaturedEventsSection with a horizontal pager and custom indicators.
- Added TopBar with location info and notification icon.
- Added EventListSection and EventCard.

---

## Screenshots (if applicable)
Include screenshots or GIFs to showcase the changes, especially if they impact the UI.

---

## Checklist
Please ensure the following tasks are completed:

- [ ] Unit tests are included for the new functionality (if applicable).
- [ ] Code has been properly documented.
- [ ] Changes have been tested and verified.
---

## Additional Comments
Add any additional information or context about the pull request here.

2024-12-25 20:32 UTC, qamarelsafadi commented on app/src/main/java/com/gdgevents/gdgeventsapp/features/event/presentaion/home/HomeScreen.kt
> +                events = listOf(
As this a dimmy data, put it in the data class so we can remove it once from there.

2024-12-25 20:44 UTC, qamarelsafadi commented on app/src/main/java/com/gdgevents/gdgeventsapp/features/event/presentaion/home/composables/EventListSection.kt
> +            items(events.size) { index ->
Pass events without events.size and use the item directly without needing doing this `val event = evevnts[index]`

2024-12-25 20:44 UTC, qamarelsafadi commented on app/src/main/java/com/gdgevents/gdgeventsapp/features/event/presentaion/home/composables/TopBar.kt
> +                painter = painterResource(id = R.drawable.ic_bell),
When we are using icon consider using vectorImage over painterResource to avoid unnecessary recomposition

2024-12-27 20:57 UTC, aarundn commented on app/src/main/java/com/gdgevents/gdgeventsapp/features/event/data/Events.kt
> +    val locationIcon: Int,
```suggestion
    @DrawableRes val locationIcon: Int,
    @DrawableRes val dateIcon: Int,
```

2024-12-28 06:36 UTC, Hossam-Elgmmal requested changes
still needs work

2024-12-28 06:36 UTC, Hossam-Elgmmal commented on app/src/main/java/com/gdgevents/gdgeventsapp/features/event/presentaion/home/composables/FeaturedEventsSection.kt
> +                    Box(
No Need for this `Box()`

2024-12-28 06:36 UTC, Hossam-Elgmmal commented on app/src/main/java/com/gdgevents/gdgeventsapp/features/event/presentaion/home/composables/FeaturedEventsSection.kt
> +        Row(
The indicator does not follow the Figma design

2024-12-28 06:36 UTC, Hossam-Elgmmal commented on app/src/main/java/com/gdgevents/gdgeventsapp/features/event/presentaion/home/composables/TopBar.kt
> +    Row(
here using `TopAppBar()` from material 3 is better

2024-12-28 06:36 UTC, Hossam-Elgmmal commented on app/src/main/java/com/gdgevents/gdgeventsapp/features/event/presentaion/home/composables/TopBar.kt
> +fun LocationInfo() {
passing a modifier here is good, it makes `LocationInfo()` reusable

2024-12-28 06:36 UTC, Hossam-Elgmmal commented on app/src/main/res/drawable/ai_image.jpg
This image is 5835 PX wide which is too large and bad for performance even as a dummy placeholder

2024-12-28 06:36 UTC, Hossam-Elgmmal commented on app/src/main/res/drawable/img_devfest.png
Why not use the full image
<img src="https://github.com/user-attachments/assets/6a7278d9-6ff8-4634-95c9-566848460247" />

2024-12-28 06:36 UTC, Hossam-Elgmmal commented on app/src/main/res/drawable/ic_bell.xml
> +    android:height="20dp"
icons should ideally have `width="24dp"`  `height="24dp"`  which is recommended by [material 3](https://m3.material.io/styles/icons/designing-icons)

2024-12-31 12:41 UTC, Hossam-Elgmmal approved these changes

2025-01-02 21:33 UTC, qamarelsafadi approved these changes
LGTM!

2025-01-03 14:59 UTC, merged