develop onboarding screen
GDGEventsApp/GDGEventsApp pull request #20
Opened 2024-12-28 19:45 UTC by aarundn

# OnBoarding Screen pull Request

## Description
this pull request implements two first scrollable Onboarding screens with pager, and get started screen design ( navigation to it not implemented ) 

---

## Changes Made
List the changes introduced in this pull request:

- adding onboard item design 
- onboard screen 
- on-board model

---

## Screenshots (if applicable)

Uploading Screenrecorder-2024-12-28-20-18-15-761[1].mp4…

---

## Checklist
Please ensure the following tasks are completed:

- [ ] Unit tests are included for the new functionality (if applicable).
- [ ] Code has been properly documented.
- [ ] Changes have been tested and verified.
---

## Additional Comments
Add any additional information or context about the pull request here.

2025-01-02 21:32 UTC, qamarelsafadi approved these changes

2025-01-02 21:32 UTC, qamarelsafadi commented on app/src/main/java/com/gdgevents/gdgeventsapp/features/onBoarding/components/OnBoardItem.kt
> +                    title = onBoardList[pagerState.currentPage].title,
```suggestion
                    val currentItem = onBoardList[pagerState.currentPage]
                    currentItem.title 
                     currentItem.description
                    
```

2025-01-02 21:32 UTC, qamarelsafadi commented on app/src/main/java/com/gdgevents/gdgeventsapp/features/onBoarding/model/OnboardModel.kt
> +        title = "To Look Up More Events or Activities Nearby By Map",
use those strings from string file

2025-01-03 14:05 UTC, Hossam-Elgmmal requested changes
Still needs work

2025-01-03 14:05 UTC, Hossam-Elgmmal commented on app/src/main/java/com/gdgevents/gdgeventsapp/features/onBoarding/components/OnBoardItem.kt
> +    device = Devices.PIXEL_3A
Previews on mobile is not what adaptive means
Adaptive layout is for large screens like tablets

2025-01-08 19:10 UTC, aarundn commented on app/src/main/java/com/gdgevents/gdgeventsapp/features/onBoarding/presentaion/OnBoardingScreen.kt
> +import android.util.Log
do not push unused imports

2025-01-11 19:33 UTC, closed without merging